### ISSUE TITLE
Error when using with `unplugin-vue-components` and SSR

### ISSUE THREAD

**Issue by AaronBeaudoin** [antfu/vite-plugin-md#112]
### Describe the bug

Minimal reproduction here (with steps in README):
https://github.com/AaronBeaudoin/vite-plugin-md-issue-weakmap-key

## Description

I have a minimal `Markdown.md` file:

```html
<Example/>
```

Where `<Example/>` is being auto-imported by `unplugin-vue-components` from `./components/Example.vue`:

```vue
<template>
  Example
</template>
```

During development, going to the page shows the text "Example" as expected.

However, after building for SSR, going to the page results in the following error:

```
[Vue warn]: Failed to resolve component: example
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
/Users/aryse/Projects/open-source/vite-plugin-md-issue-weakmap-key/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3927
        cache.set(comp, shared.EMPTY_ARR);
              ^

TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (/Users/aryse/Projects/open-source/vite-plugin-md-issue-weakmap-key/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3927:15)
    at createComponentInstance (/Users/aryse/Projects/open-source/vite-plugin-md-issue-weakmap-key/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6957:23)
    at renderComponentVNode (/Users/aryse/Projects/open-source/vite-plugin-md-issue-weakmap-key/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:171:22)
    at ssrRenderComponent (/Users/aryse/Projects/open-source/vite-plugin-md-issue-weakmap-key/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:608:12)
    at file:///Users/aryse/Projects/open-source/vite-plugin-md-issue-weakmap-key/dist/server/server.mjs:11:13
    at renderComponentSubTree (/Users/aryse/Projects/open-source/vite-plugin-md-issue-weakmap-key/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:253:13)
    at renderComponentVNode (/Users/aryse/Projects/open-source/vite-plugin-md-issue-weakmap-key/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:188:16)
    at renderVNode (/Users/aryse/Projects/open-source/vite-plugin-md-issue-weakmap-key/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:295:22)
    at renderComponentSubTree (/Users/aryse/Projects/open-source/vite-plugin-md-issue-weakmap-key/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:259:13)
```

### Reproduction

https://github.com/AaronBeaudoin/vite-plugin-md-issue-weakmap-key

### System Info

```Shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 168.19 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Safari: 15.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by brillout** [comment]
The reproduction Aaron provided uses [Vite's SSR API](https://vitejs.dev/guide/ssr.html).

This means that this bug affects all Vite frameworks ([vite-plugin-ssr - #422](https://github.com/brillout/vite-plugin-ssr/issues/422), Nuxt, ...).

**Comment by AaronBeaudoin** [comment]
Just bringing attention back to this issue at the 3 week mark.

**Comment by yankeeinlondon** [comment]
@AaronBeaudoin please try [Release v0.22.0](https://github.com/antfu/vite-plugin-md/releases/tag/v0.22.0) and see if it fixes your error? If not then do note @brillout comment that there error is directly related to a different repo. Reopen if it is still an issue ok?

**Comment by brillout** [comment]
@yankeeinlondon The [latest tag](https://www.npmjs.com/package/vite-plugin-md?activeTab=versions) still points to the `0.21.x` release branch. So I guess the `0.22.x` branch is beta? (I couldn't find any mention of `0.22.x` in the readme.)

**Comment by yankeeinlondon** [comment]
@brillout i've been trying to clear out some dependencies so I can do another release on this ... I _had_ thought I'd released v22 though but I'll check in the next day or too. Sorry for the delays.
