### ISSUE TITLE
Markdown is not a function

### ISSUE THREAD

**Issue by i-ez** [antfu/vite-plugin-md#20]
Markdown is not a function
    at file:///E:/ez/ez-vite/vite.config.ts.js
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async loadConfigFromFile (E:\ez\ez-vite\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:75464:31)
    at async resolveConfig (E:\ez\ez-vite\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:75096:28)
    at async createServer (E:\ez\ez-vite\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:73625:20)
    at async CAC.<anonymous> (E:\ez\ez-vite\node_modules\vite\dist\node\cli.js:13963:24)

**Comment by i-ez** [comment]
my vite.config.ts file
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'
import legacy from '@vitejs/plugin-legacy'
import Markdown from 'vite-plugin-md'
import path from 'path'
import pkgJson from './package.json'

const resolve = path.resolve
// https://vitejs.dev/config/
export default defineConfig({
  base: '/1x/',
  server: {
    port: 5000,
    proxy: {
      '/devServer': {
        target: 'https://ezui.com',
        changeOrigin: true,
        rewrite: path => path.replace(/^\/devServer/, ''),
      },
    },
  },
  resolve: {
    alias: {
      '@': '/src',
    },
  },
  plugins: [
    vue({
      include: [/\.vue$/, /\.md$/],
    }),
    vueJsx(),
    Markdown(),
    legacy({
      targets: ['defaults', 'not IE 11'],
    }),
  ],
  build: {
    target: 'es2015',
    outDir: './dist/1x/',
    assetsDir: pkgJson.version,
    cssCodeSplit: true,
    // rollupOptions: {
    //   input: {
    //     doc: resolve(__dirname, 'index.html'),
    //     mobile: resolve(__dirname, 'demo.html'),
    //   },
    // },
  },
})
```

**Comment by yankeeinlondon** [comment]
@i-ez can you produce a minimally reproducible example of this issue or shall we close this?
